server:
  port: 80
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: fact
      # 自动将字段转换为驼峰标识存储到mongo中.
      field-naming-strategy:  org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      username: xxx
      password: xxxx
license:
  encryptKey: testhaha
  initGenCount: 10
